### PR TITLE
Added patch to plugins

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by baconpaul** [comment]
Hi!

Just curious - are you going to upstream that patch? And what's the condition in which that actually breaks?

Best

**Comment by hfiguiere** [comment]
I will submit a PR. As for the conditions, no idea. Just that -1 is returned and the used as an array index.

And since we build with assertions on, it crashes.

**Comment by hfiguiere** [comment]
it's new with 1.1.1 it seems (didn't have it in 1.1.0)

**Comment by baconpaul** [comment]
Huh odd. Thanks! Wonder what changed but appreciate the PR :)

**Comment by hfiguiere** [comment]
filed as https://github.com/surge-synthesizer/surge/pull/6608

**Comment by baconpaul** [comment]
Thanks! I merged that and we will include it in 1.1.2

**Pull request merged**
