### PR TITLE
Update to Surge-XT 1.3.0

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
The plugin display a black screen on my setup. Unless I put Ardour on the other screen, but then it's zoomed way to much and the UI is truncated.... on a 4K screen.

**Comment by hfiguiere** [comment]
On the laptop it show the UI, but it is stuck at 125% and I can't set to less than that. At 125% it doesn't fit the screen.

**Comment by baconpaul** [comment]
Is that with the VST3 or the LV2? Are you applying any patches or changing any of our dependencies?

We really haven't tested the LV2 at all since we moved to JUCE 7.

**Comment by hfiguiere** [comment]
The LV2 can't be built, so it's only the VST3. In Ardour. On my laptop it behaves differently.

On the big rig™, if I have Ardour on the 4K display, I get a black content for the Surge-XT plugin. If Ardour is on the other display, Surge-XT plugin is over zoomed on the 4K screen and the UI doesn't even fit in it.

On the laptop (one screen) it is displayed at 125% and I can't change that and that cause the UI to not fit on the screen.

Both run Wayland so the X11 display is done by XWayland. And it's gnome-shell.

**Comment by baconpaul** [comment]
hmm. we dont do anything special we just upgraded to juce 7. do you have any other daws you can test with?

It's been a couple of weeks since i ran the plugin on linux but bitwig ubuntu 22 worked fine for me when i tried.

**Comment by hfiguiere** [comment]
On the laptop it seems to work fine with Carla.

**Comment by hfiguiere** [comment]
Only using the VST3.
On the big rig™ where there problems are visible:

- it works in Carla
- standalone wokrs
- 1.2.3 also fails in Ardour 8.1. I'm pretty sure it worked before, here are the changes in config:
  - I very recently added a second screen a 4K that is now the main one - not sure I ran Surge-XT in that setup.
  - as a consquence Ardour font scaling got increased to be readable on 4K.
- I disabled the non 4K and problem occur still.

So I think my config is triggering a certain number of issues.

Note that on the laptop it seems to never want to scale back to 100%, and the UI doesn't fit, and this seems to happen with 1.2.3 as well.

Interestingly, with 1.2.3 the LV2 at 125% has a smaller UI than the VST3 (locked at 125%). 150% in LV2 is a closer match.

**Comment by hfiguiere** [comment]
Upon further analysis, it seems that it is Ardour with a UI scale.

font-scale set to 150000, and I get a black window
font-scale set to 128000, and I get a huge window: see the comparison Ardour vs Surge XT

image

Ardour do support UI scaling and pass it on. It look like that the plugin is scaled twice.

**Comment by hfiguiere** [comment]
In Ardour it sets the UI scaling

https://github.com/Ardour/ardour/blob/master/gtk2_ardour/vst3_plugin_ui.cc#L107

**Comment by x42** [comment]
>  font-scale set to 128000, and I get a huge window: see the comparison Ardour vs Surge XT

The default is `102400` (originates from pango/cairo). So for a ui-scale of 128k. Ardour report   `1.25`  via VST3's `Presonus::IPlugInViewScaling` extension.

**Comment by hfiguiere** [comment]
Filed https://github.com/surge-synthesizer/surge/issues/7396 upstream

**Comment by hfiguiere** [comment]
Now my only concern is the removal of LV2. There is little I can do about it for now.

**Comment by baconpaul** [comment]
The LV2 builds. we can't get it building in our CI pipeline and we haven't had any user have a better experience with it than they did with the VST3. But if you add `-DSURGE_BUILD_LV2` to your command line it will run the juce 7 LV2 build process.

**Comment by hfiguiere** [comment]
> The LV2 builds. we can't get it building in our CI pipeline and we haven't had any user have a better experience with it than they did with the VST3.

The scaling problem doesn't occur

> But if you add `-DSURGE_BUILD_LV2` to your command line it will run the juce 7 LV2 build process.

I have the exact same problem you have: the lv2 helper crashes because there is no X11.

**Pull request merged**
